name: Development

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.0']
        elixir: ['1.12.2']
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Setup OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Get Deps Cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: |
            deps
            _build
            priv/plts
        key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-${{hashFiles('mix.lock')}}-build

    - name: Install Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: | 
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
   
    - name: Compile
      run: mix compile --warnings-as-errors
  static_code_analysis:
    name: Static Code Analysis
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.0']
        elixir: ['1.12.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Check Code Format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo
  tests:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ['24.0']
        elixir: ['1.12.2']

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Check seeds consistency
        run: | 
          mix ecto.create
          mix ecto.migrate
          mix run priv/repo/seeds.exs
      - name: Run test
        run: mix test
